import Head from "next/head";
import styles from "../styles/Home.module.css";
import { auth, provider } from "../firebase";

export default function Home() {
  const signIn = () => {
    auth
      .signInWithRedirect(provider)
      .then((result) => {
        console.log(result);
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Next.js authentication with Firebase</h1>
      <button onClick={signIn}>Sign In</button>
      <button onClick={() => auth.signOut()}>Sign Out</button>
    </div>
  );
}
